import{createServer}from'node:http';import{existsSync,readFileSync}from'node:fs';import{resolve}from'node:path';
const root=process.cwd();
function loadEnv(file){if(!existsSync(file))return;for(const line of readFileSync(file,'utf8').split(/\r?\n/)){const match=line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/i);if(!match||process.env[match[1]])continue;process.env[match[1]]=match[2].replace(/^['"]|['"]$/g,'')}}
loadEnv(resolve(root,'.env.local'));loadEnv(resolve(root,'.env'));
const port=Number(process.env.DEEPSEEK_PROXY_PORT||3001),apiKey=process.env.DEEPSEEK_API_KEY,model=process.env.DEEPSEEK_MODEL||'deepseek-chat',visionModel=process.env.DEEPSEEK_VISION_MODEL||model;
const allowedOrigins=new Set(['http://127.0.0.1:5173','http://localhost:5173']);
function cors(res,origin){res.setHeader('Access-Control-Allow-Origin',allowedOrigins.has(origin)?origin:'http://127.0.0.1:5173');res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS')}
function json(res,status,payload,origin){cors(res,origin);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(payload))}
function readBody(req){return new Promise((resolveBody,reject)=>{let raw='';req.on('data',chunk=>{raw+=chunk;if(raw.length>8_000_000){req.destroy();reject(new Error('请求上下文过大'))}});req.on('end',()=>{try{resolveBody(JSON.parse(raw||'{}'))}catch{reject(new Error('请求不是有效 JSON'))}});req.on('error',reject)})}
function buildUserPrompt({prompt,context}){const safeContext={category:String(context?.category||''),stem:String(context?.stem||''),options:Array.isArray(context?.options)?context.options.map(String).slice(0,10):[],feedback:Array.isArray(context?.feedback)?context.feedback.map(String).slice(0,12):[]};return`当前题目上下文（只用于本次回答）：\n${JSON.stringify(safeContext,null,2)}\n\n用户追问：\n${String(prompt||'').slice(0,4000)}`}
function buildUserContent(body){const text=buildUserPrompt(body);const images=Array.isArray(body.images)?body.images.filter(item=>typeof item==='string'&&item.startsWith('data:image/')).slice(0,4):[];if(!images.length)return text;return[{type:'text',text},...images.map(url=>({type:'image_url',image_url:{url}}))]}
const server=createServer(async(req,res)=>{const origin=req.headers.origin||'';if(req.method==='OPTIONS'){cors(res,origin);res.writeHead(204);return res.end()}if(req.method!=='POST'||req.url!=='/api/assistant')return json(res,404,{error:'NOT_FOUND'},origin);if(!apiKey)return json(res,503,{error:'AI_NOT_CONFIGURED',message:'本机尚未配置 DeepSeek API Key。'},origin);try{const body=await readBody(req);if(!body.prompt)return json(res,400,{error:'PROMPT_REQUIRED'},origin);const hasImages=Array.isArray(body.images)&&body.images.some(item=>typeof item==='string'&&item.startsWith('data:image/'));const requestedModel=typeof body.model==='string'&&/^[a-z0-9._:-]{1,80}$/i.test(body.model)?body.model.trim():'';const requestModel=requestedModel||(hasImages?visionModel:model);const upstream=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:requestModel,messages:[{role:'system',content:'你是职业测评题目辅导助手。请用中文回答，先给结论，再解释依据；不要编造题目中没有的信息。图形题如果有图片，请先按视觉特征分类，再说明应优先验证的规律，最后结合选项给出结论；如果缺少图片，要明确说明无法仅凭文字确认，并给出观察框架。回答要具体、分层、便于刷题复盘。'},{role:'user',content:buildUserContent(body)}],temperature:.25,max_tokens:1200})});const data=await upstream.json().catch(()=>({}));if(!upstream.ok)return json(res,502,{error:'DEEPSEEK_REQUEST_FAILED',message:data?.error?.message||`DeepSeek 请求失败（${upstream.status}）`},origin);const answer=data?.choices?.[0]?.message?.content?.trim();if(!answer)return json(res,502,{error:'EMPTY_AI_RESPONSE',message:'DeepSeek 没有返回有效回答。'},origin);return json(res,200,{answer,model:requestModel},origin)}catch(error){return json(res,500,{error:'PROXY_ERROR',message:error.message||'本机 AI 代理发生错误。'},origin)}});
server.listen(port,'127.0.0.1',()=>console.log(`DeepSeek 本机代理已启动：http://127.0.0.1:${port}`));
