import{getPdfRuntime}from'./pdfRuntime.js';
const DB='beisen-question-files',STORE='pdfs';
const documentCache=new Map(),renderCache=new Map(),MAX_RENDER_CACHE=48;
function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore(STORE);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function savePdf(id,file){const database=await db(),bytes=await file.arrayBuffer();await new Promise((resolve,reject)=>{const tx=database.transaction(STORE,'readwrite');tx.objectStore(STORE).put(bytes,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});database.close()}
export async function deletePdf(id){const database=await db();await new Promise((resolve,reject)=>{const tx=database.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});database.close();const cached=documentCache.get(id);documentCache.delete(id);cached?.then(pdf=>pdf?.destroy?.()).catch(()=>{});for(const key of renderCache.keys())if(key.startsWith(`${id}:`))renderCache.delete(key)}
async function loadBytes(id){const database=await db(),value=await new Promise((resolve,reject)=>{const req=database.transaction(STORE).objectStore(STORE).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});database.close();return value}
export async function loadPdfBytes(id){return loadBytes(id)}
async function loadDocument(id){let promise=documentCache.get(id);if(!promise){promise=(async()=>{const bytes=await loadBytes(id);if(!bytes)return null;const{getDocument}=await getPdfRuntime();return getDocument({data:new Uint8Array(bytes)}).promise})().catch(error=>{documentCache.delete(id);throw error});documentCache.set(id,promise)}return promise}
export async function renderStoredPage(id,pageNumber,crop){const key=`${id}:${pageNumber}:${crop?`${crop.top}-${crop.bottom}`:'full'}`;if(renderCache.has(key)){const cached=renderCache.get(key);renderCache.delete(key);renderCache.set(key,cached);return cached}const pdf=await loadDocument(id);if(!pdf)return null;const page=await pdf.getPage(pageNumber),viewport=page.getViewport({scale:crop?2:1.15}),full=document.createElement('canvas');full.width=viewport.width;full.height=viewport.height;await page.render({canvasContext:full.getContext('2d'),viewport}).promise;let result;if(!crop)result=full.toDataURL('image/jpeg',.82);else{const top=Math.max(0,Math.floor(full.height*crop.top)),bottom=Math.min(full.height,Math.ceil(full.height*crop.bottom)),out=document.createElement('canvas');out.width=full.width;out.height=Math.max(120,bottom-top);out.getContext('2d').drawImage(full,0,top,full.width,out.height,0,0,full.width,out.height);result=out.toDataURL('image/jpeg',.9)}renderCache.set(key,result);while(renderCache.size>MAX_RENDER_CACHE)renderCache.delete(renderCache.keys().next().value);return result}
